### ISSUE TITLE
Add a priority field 

### ISSUE THREAD

**Issue by Barraza44** [Code2Gether-Discord/BusyList#37]
### Elevator pitch: Priority field
Allows tasks to be asigned to a certain priority (Low, Medium, High).

### Describe how this new feature adds value to the application
By having priorities, users can easily see which tasks are more important than others so they can decide which ones to work on first.

### Describe suggested implementation
We could edit the parsing grammar for add command to make it similar to edit command in #35 such as: `add [description] [priority]`. It could even be a single letter like H for high, M for medium and L for low.

**Comment by pobiega** [comment]
Good idea. Much like labels, it will need a unique pattern and go before the description, to avoid parsing problems.

My suggestion would be `add [p:<L|M|H|l|m|h|low|medium|high>] <description>`, and obviously the edit command will have to support it as well.
