### ISSUE TITLE
Discussion: define the Minimum Viable Product (MVP)

### ISSUE THREAD

**Issue by pobiega** [Code2Gether-Discord/BusyList#8]
In order to not feature-creep and actually get a useful program sometime soon (that we can later expand on), it's very important to define exactly what the MVP contains. For this kind of program, it makes sense to define that as what commands do we support.

This is a discussion issue. That means you are encouraged to come with ideas, feedback, criticism and suggestions. Keep in mind that only the **BARE MINIMUM** should be included here. More features can be added once these are done.

My suggestions for an MVP are...

- command: add (add a new task)
- command: delete (delete an existing task)
- command: read (show the details on a specified task)
- command: done (mark a task as done)
- command: list (show all tasks in the system)
- feature: persistence (saving and loading of task list between runs)

**Comment by 18-F-cali** [comment]
Lets get started with these.

**Comment by SquallyWally** [comment]
You took the words from my mouth with these MVP suggestions.

**Comment by cairog** [comment]
It looks good, lets start with this.

**Comment by SquallyWally** [comment]
I come to a supposition that we can close this issue, unless more people want to chip in.

**Comment by pobiega** [comment]
Agreed, everyone seems to think this is a good MVP scope.
