### ISSUE TITLE
Discussion: Persistance

### ISSUE THREAD

**Issue by pobiega** [Code2Gether-Discord/BusyList#9]
We need a way to save tasks between the runs of the program.

For the MVP, we want to keep this simple and easy, yet working. That means no EntityFramework (way to complicated), no SQL servers or anything like that.

I suggest we simply save it to a file on the harddrive, as that is the simpliest way I can think of.

Any other suggestions? If we go with the file route, what format do we use? JSON seems like a good choice since its human readable, literally one line of code to read or write and handles adding/removing fields from the object stored quite well.

**Comment by SquallyWally** [comment]
Our initial thought was either saving it on a CSV or JSON. At this moment I have experience to save everything on CSV but I can imagine how easy it is to work with JSON.  

But yes saving on a harddrive sounds like the most logical way at this moment. SQL can be a feature after the initial implementation is complete ( if there is still interest in)

**Comment by denislavh** [comment]
I like the idea about json serialization and maybe we can add a save command that serializes all the newly create tasks.

**Comment by chrisK00** [comment]
Json sounds good

**Comment by pobiega** [comment]
JSON seems to be the call here. Closing this and making an implementation issue.
